// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbujMd_b4jEU_nQX7OhExUiRf183PtABQ',
    appId: '1:1049245256739:web:7866341a2271b731af7596',
    messagingSenderId: '1049245256739',
    projectId: 'vuthaian-213e6',
    authDomain: 'vuthaian-213e6.firebaseapp.com',
    databaseURL: 'https://vuthaian-213e6-default-rtdb.firebaseio.com',
    storageBucket: 'vuthaian-213e6.appspot.com',
    measurementId: 'G-7MMH1Y6Q5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpk1BPGYCgxFZsCAoEOlimntkH84XV3L4',
    appId: '1:1049245256739:android:db0a2d7a1b4aee53af7596',
    messagingSenderId: '1049245256739',
    projectId: 'vuthaian-213e6',
    databaseURL: 'https://vuthaian-213e6-default-rtdb.firebaseio.com',
    storageBucket: 'vuthaian-213e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEGg246eZAmFz4n0975VPRulCEfnSCz9w',
    appId: '1:1049245256739:ios:e2ba5bea5322f6f8af7596',
    messagingSenderId: '1049245256739',
    projectId: 'vuthaian-213e6',
    databaseURL: 'https://vuthaian-213e6-default-rtdb.firebaseio.com',
    storageBucket: 'vuthaian-213e6.appspot.com',
    iosBundleId: 'com.example.ungdunggiuaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEGg246eZAmFz4n0975VPRulCEfnSCz9w',
    appId: '1:1049245256739:ios:e2ba5bea5322f6f8af7596',
    messagingSenderId: '1049245256739',
    projectId: 'vuthaian-213e6',
    databaseURL: 'https://vuthaian-213e6-default-rtdb.firebaseio.com',
    storageBucket: 'vuthaian-213e6.appspot.com',
    iosBundleId: 'com.example.ungdunggiuaki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbujMd_b4jEU_nQX7OhExUiRf183PtABQ',
    appId: '1:1049245256739:web:9cf371382d624f0faf7596',
    messagingSenderId: '1049245256739',
    projectId: 'vuthaian-213e6',
    authDomain: 'vuthaian-213e6.firebaseapp.com',
    databaseURL: 'https://vuthaian-213e6-default-rtdb.firebaseio.com',
    storageBucket: 'vuthaian-213e6.appspot.com',
    measurementId: 'G-GYSQR2PXKN',
  );
}
